name: "Assign Reviewers"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: "Assign Team and Persons"
        uses: rowi1de/auto-assign-review-teams@v0.0.6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          teams: "practice-teams"         # only works for GitHub Organisation/Teams
          persons: "kyungjin"            # add individual persons here
          include-draft: false            # Draft PRs will be skipped (default: false)
          skip-with-manual-reviewers: 9   # Skip this action, if the number of reviwers was already assigned (default: 0)

# This is a basic workflow to help you get started with Actions

#name: 'Auto Assign Test'
#
## Controls when the action will run. Triggers the workflow on push or pull request
## events but only for the master branch
#on:
#  pull_request
#
#jobs:
#  assign-reviewers:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: kentaro-m/auto-assign-action@v1.1.1
#        with:
#          cofiguration-path: ".github/auto_assign.yml"
#     branches: [ master ]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2

#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!

#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
